# 基本配置
base:
  # 客户端模组文件夹
  mod-folder: ".minecraft/mods"
# 同步服务器连接配置
server:
  host: "127.0.0.1"
  port: 25566
# 文件同步相关配置
sync:
  # 同步时同时下载的模组数量
  fetch-concurrency: 2
  # 软删除
  soft-remove: true
  # 是否同步服务端提供的客户端辅助类型模组
  fetch-client-mods: false
  # 忽略同步的模组文件名列表
  # 对于忽略同步的模组，不会被视为多余模组而被删除
  ignore-file-names:
    - "example-mod.jar"
# 退出延迟，同步完成后延迟多少秒退出，若设为0则同步完成立即退出
# 建议设定延迟几秒，以便于查看同步日志，排查错误
exit-delay: 3